---
distroname: debian7
distrotype: debianwheezy
debianname: wheezy
minram: 256
installconfigfile: "el6/kickstart.cfg"
injectfile: preseed.cfg
location: http://be.mirror.eurid.eu/debian/dists/wheezy/main/installer-amd64/
mirrorcountry: be
mirrorurl: ftp.be.debian.org
mirrordir: /debian
textrargs: "auto=true DEBIAN_FRONTEND=text noshell fb=false console=ttyS0,115200 lowmem"
webserver: www
webpath: /var/www/html/
weburl: http://www.example.com/
